version: '3'

services:
  database:
    image: mysql:5.6
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: statistics
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  php:
    build:
      context: .
    volumes:
    - "../backend/:/opt/project/backend"
    - "./:/opt/project/dev"

  webserver:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
    - "./nginx/:/etc/nginx/conf.d/"
    - "../:/opt/project"
